---
title: "IODS final project"
author: "Sampsa Huttunen"
date: February 26, 2017
email: sampsa.huttunen@helsinki.fi
output:
  html_document:
    theme: lumen
    toc: true
    toc_depth: 2
    fig_caption: true
    fig_width: 6
    fig_height: 4
    code_folding: hide
---

## Abstract

An 'abstract' at the beginning of the page with a summary of your analysis  

## 1 Research Question

Brief description of the "research question" you are exploring, possibly including your hypothesis  

## 2 Data Wrangling

I have created a new dataset named 'kasistuet-sukup' from the original dataset 'SES Tukipäätökset 2008-2015.csv'.

##### Data Files:  
* The original dataset (SES_Tukipaeaetoekset_2008-2015.csv) can be found [here](http://ses.fi/fileadmin/dokumentit/SES_Tukipaeaetoekset_2008-2015.csv)  
* The new dataset (analysis_dataset.csv) can be found [here](https://github.com/huttusam/IODS-final/blob/master/data/kasistuet-sukup.csv)  

##### Script:  
* The R script used to create the new dataset (*with comments explaining the process*) is  [here](https://github.com/huttusam/IODS-final/blob/master/final-assignment.R)

## 3 Data and Variables

Description of your data and its variables  
Where is the data from  
what does it relate to  
what do the variables represent  
what has been done to the data before analysis  

## 4 Analysis

Visually clear and interesting explorations of the variables of interest in the data, from the point of view of your research question. Include interpretations of the distributions and relationships of the variables. Use captions to draw the reader's focus on the interesting parts of your tables and graphics.  

## 5 Methodology

Brief description of the method you are using in your own words.  

## 6 Results

Presentation of the results of your analysis including visualizations and summaries and a thorough interpretation of the results including a validation analysis of the method.  

## 7 Conclusions and Discussion



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


